services:
  - type: web
    name: shreerangdesigns-backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: FRONTEND_URL
        value: https://shreerangdesigns.in
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: PHONEPE_MERCHANT_ID
        sync: false
      - key: PHONEPE_SECRET_KEY
        sync: false
      - key: PHONEPE_BASE_URL
        value: https://api.phonepe.com

  - type: static
    name: shreerangdesigns-frontend
    buildCommand: npm run build
    staticPublishPath: dist
    envVars:
      - key: NODE_ENV
        value: production
